language: go

services:
  - docker

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

env: GO111MODULE=on

git:
  depth: 1

branches:
  only:
    - master
    - release

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -v -race ./...

after_success:
  - docker build -t stanyx/shortly -f ./deploy/Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push stanyx/shortly