language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

env: GO111MODULE=on

git:
  depth: 1

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -v -race ./...