Database:
  Host: localhost
  Port: 5432
  User: shortly_user
  Password: 1
  Database: shortly
Cache:
  CacheType: "memcached"
  Memcached:
    Server: localhost:11211
  BoltDB:
    Dir: .
Auth:
  Secret: "secret"
Billing:
  Payment:
    Key: ''
    WebhookKey: ''
LinkDB:
  Dir: .
ServiceDB:
  Dir: .
RedirectLogger:
  Storage: postgres
  Mode: sync
  Redis:
    Port: 6379
GeoIP:
  DownloadURL: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=%s&suffix=tar.gz'
  DatabasePath: ./downloads/
  LicenseKey: 'GrJyMeHTORrjqrY3'