Database:
  Host: localhost
  Port: 5432
  User: shortly_user
  Password: 1
  Database: shortly
Cache:
  CacheType: "boltdb"
  Memcached:
    ServerList:
      - localhost:11211
  BoltDB:
    Dir: .
Auth:
  Secret: "secret"
Billing:
  Payment:
    Key: 'sk_test_mQj3xODJwHwIer0DuaRPTLpD00felDhCRp'
    WebhookKey: whsec_htM4fNMt9NS8rVWRcrlXzE0PnGXEzsBp
LinkDB:
  Dir: .
ServiceDB:
  Dir: .
RedirectLogger:
  Storage: postgres
  Mode: sync
  Redis:
    Port: 6379