basePath: /api/v1
definitions:
  response.ApiResponse:
    properties:
      result:
        type: object
    type: object
info:
  contact: {}
  description: Url shortener web application.
  license: {}
  title: Shortly API
  version: "1.0"
paths:
  /:
    get:
      operationId: redirect-short-link
      responses:
        "307": {}
        "308": {}
        "400": {}
        "500": {}
      summary: Redirect from short link to associated long url
      tags:
      - Links
  /tags/create:
    post:
      description: read campaigns list for current authorized account
      operationId: get-all-campaigns
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      tags:
      - Campaigns
  /users:
    get:
      operationId: get-users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Retrieve all users for current account
      tags:
      - Users
swagger: "2.0"
